// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AgencyProtocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Agency.Network.Protobuffprotocol {

  /// <summary>Holder for reflection information generated from AgencyProtocol.proto</summary>
  public static partial class AgencyProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for AgencyProtocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AgencyProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRBZ2VuY3lQcm90b2NvbC5wcm90bxIgYWdlbmN5Lm5ldHdvcmsucHJvdG9i",
            "dWZmcHJvdG9jb2wiKwoIRW1wbG95ZWUSDQoFZW1haWwYASABKAkSEAoIcGFz",
            "c3dvcmQYAiABKAkiMwoKRmlsdGVyRGF0YRITCgtkZXN0aW5hdGlvbhgBIAEo",
            "CRIQCghkYXRldGltZRgCIAEoCSJkCgZGbGlnaHQSEAoIRmxpZ2h0SUQYASAB",
            "KAUSEwoLZGVzdGluYXRpb24YAiABKAkSEAoIZGF0ZXRpbWUYAyABKAkSDwoH",
            "YWlycG9ydBgEIAEoCRIQCghub1BsYWNlcxgFIAEoBSKVAQoGVGlja2V0EhIK",
            "CmNsaWVudE5hbWUYASABKAkSFAoMdG91cmlzdE5hbWVzGAIgASgJEhUKDWNs",
            "aWVudEFkZHJlc3MYAyABKAkSEAoIbm9QbGFjZXMYBCABKAUSOAoGZmxpZ2h0",
            "GAUgASgLMiguYWdlbmN5Lm5ldHdvcmsucHJvdG9idWZmcHJvdG9jb2wuRmxp",
            "Z2h0IvUCCg1BZ2VuY3lSZXF1ZXN0EkIKBHR5cGUYASABKA4yNC5hZ2VuY3ku",
            "bmV0d29yay5wcm90b2J1ZmZwcm90b2NvbC5BZ2VuY3lSZXF1ZXN0LlR5cGUS",
            "PAoIZW1wbG95ZWUYAiABKAsyKi5hZ2VuY3kubmV0d29yay5wcm90b2J1ZmZw",
            "cm90b2NvbC5FbXBsb3llZRJHChFmaWx0ZXJfZGF0YV9hcnJheRgDIAEoCzIs",
            "LmFnZW5jeS5uZXR3b3JrLnByb3RvYnVmZnByb3RvY29sLkZpbHRlckRhdGES",
            "OAoGdGlja2V0GAQgASgLMiguYWdlbmN5Lm5ldHdvcmsucHJvdG9idWZmcHJv",
            "dG9jb2wuVGlja2V0Il8KBFR5cGUSCwoHVW5rbm93bhAAEgkKBUxvZ2luEAES",
            "CgoGTG9nb3V0EAISDwoLR2V0X2ZsaWdodHMQAxIOCgpCdXlfdGlja2V0EAQS",
            "EgoORmlsdGVyX2ZsaWdodHMQBSKeAwoOQWdlbmN5UmVzcG9uc2USQwoEdHlw",
            "ZRgBIAEoDjI1LmFnZW5jeS5uZXR3b3JrLnByb3RvYnVmZnByb3RvY29sLkFn",
            "ZW5jeVJlc3BvbnNlLlR5cGUSDQoFZXJyb3IYAiABKAkSOQoHZmxpZ2h0cxgD",
            "IAMoCzIoLmFnZW5jeS5uZXR3b3JrLnByb3RvYnVmZnByb3RvY29sLkZsaWdo",
            "dBI8CghlbXBsb3llZRgEIAEoCzIqLmFnZW5jeS5uZXR3b3JrLnByb3RvYnVm",
            "ZnByb3RvY29sLkVtcGxveWVlEjgKBnRpY2tldBgFIAEoCzIoLmFnZW5jeS5u",
            "ZXR3b3JrLnByb3RvYnVmZnByb3RvY29sLlRpY2tldBI4CgZmbGlnaHQYBiAB",
            "KAsyKC5hZ2VuY3kubmV0d29yay5wcm90b2J1ZmZwcm90b2NvbC5GbGlnaHQi",
            "SwoEVHlwZRILCgdVbmtub3duEAASBgoCT2sQARIJCgVFcnJvchACEg8KC0dl",
            "dF9mbGlnaHRzEAMSEgoOVXBkYXRlX2ZsaWdodHMQBEIzCiBhZ2VuY3kubmV0",
            "d29yay5wcm90b2J1ZmZwcm90b2NvbEIPQWdlbmN5UHJvdG9idWZzYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Agency.Network.Protobuffprotocol.Employee), global::Agency.Network.Protobuffprotocol.Employee.Parser, new[]{ "Email", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Agency.Network.Protobuffprotocol.FilterData), global::Agency.Network.Protobuffprotocol.FilterData.Parser, new[]{ "Destination", "Datetime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Agency.Network.Protobuffprotocol.Flight), global::Agency.Network.Protobuffprotocol.Flight.Parser, new[]{ "FlightID", "Destination", "Datetime", "Airport", "NoPlaces" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Agency.Network.Protobuffprotocol.Ticket), global::Agency.Network.Protobuffprotocol.Ticket.Parser, new[]{ "ClientName", "TouristNames", "ClientAddress", "NoPlaces", "Flight" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Agency.Network.Protobuffprotocol.AgencyRequest), global::Agency.Network.Protobuffprotocol.AgencyRequest.Parser, new[]{ "Type", "Employee", "FilterDataArray", "Ticket" }, null, new[]{ typeof(global::Agency.Network.Protobuffprotocol.AgencyRequest.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Agency.Network.Protobuffprotocol.AgencyResponse), global::Agency.Network.Protobuffprotocol.AgencyResponse.Parser, new[]{ "Type", "Error", "Flights", "Employee", "Ticket", "Flight" }, null, new[]{ typeof(global::Agency.Network.Protobuffprotocol.AgencyResponse.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Employee : pb::IMessage<Employee>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Employee> _parser = new pb::MessageParser<Employee>(() => new Employee());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Employee> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Agency.Network.Protobuffprotocol.AgencyProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Employee() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Employee(Employee other) : this() {
      email_ = other.email_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Employee Clone() {
      return new Employee(this);
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 1;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Employee);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Employee other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Email != other.Email) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Email.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Email);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Email.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Email);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Employee other) {
      if (other == null) {
        return;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Email = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Email = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class FilterData : pb::IMessage<FilterData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FilterData> _parser = new pb::MessageParser<FilterData>(() => new FilterData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FilterData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Agency.Network.Protobuffprotocol.AgencyProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilterData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilterData(FilterData other) : this() {
      destination_ = other.destination_;
      datetime_ = other.datetime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilterData Clone() {
      return new FilterData(this);
    }

    /// <summary>Field number for the "destination" field.</summary>
    public const int DestinationFieldNumber = 1;
    private string destination_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Destination {
      get { return destination_; }
      set {
        destination_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "datetime" field.</summary>
    public const int DatetimeFieldNumber = 2;
    private string datetime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Datetime {
      get { return datetime_; }
      set {
        datetime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FilterData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FilterData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Destination != other.Destination) return false;
      if (Datetime != other.Datetime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Destination.Length != 0) hash ^= Destination.GetHashCode();
      if (Datetime.Length != 0) hash ^= Datetime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Destination.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Destination);
      }
      if (Datetime.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Datetime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Destination.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Destination);
      }
      if (Datetime.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Datetime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Destination.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Destination);
      }
      if (Datetime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Datetime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FilterData other) {
      if (other == null) {
        return;
      }
      if (other.Destination.Length != 0) {
        Destination = other.Destination;
      }
      if (other.Datetime.Length != 0) {
        Datetime = other.Datetime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Destination = input.ReadString();
            break;
          }
          case 18: {
            Datetime = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Destination = input.ReadString();
            break;
          }
          case 18: {
            Datetime = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Flight : pb::IMessage<Flight>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Flight> _parser = new pb::MessageParser<Flight>(() => new Flight());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Flight> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Agency.Network.Protobuffprotocol.AgencyProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Flight() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Flight(Flight other) : this() {
      flightID_ = other.flightID_;
      destination_ = other.destination_;
      datetime_ = other.datetime_;
      airport_ = other.airport_;
      noPlaces_ = other.noPlaces_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Flight Clone() {
      return new Flight(this);
    }

    /// <summary>Field number for the "FlightID" field.</summary>
    public const int FlightIDFieldNumber = 1;
    private int flightID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FlightID {
      get { return flightID_; }
      set {
        flightID_ = value;
      }
    }

    /// <summary>Field number for the "destination" field.</summary>
    public const int DestinationFieldNumber = 2;
    private string destination_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Destination {
      get { return destination_; }
      set {
        destination_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "datetime" field.</summary>
    public const int DatetimeFieldNumber = 3;
    private string datetime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Datetime {
      get { return datetime_; }
      set {
        datetime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "airport" field.</summary>
    public const int AirportFieldNumber = 4;
    private string airport_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Airport {
      get { return airport_; }
      set {
        airport_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "noPlaces" field.</summary>
    public const int NoPlacesFieldNumber = 5;
    private int noPlaces_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NoPlaces {
      get { return noPlaces_; }
      set {
        noPlaces_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Flight);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Flight other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FlightID != other.FlightID) return false;
      if (Destination != other.Destination) return false;
      if (Datetime != other.Datetime) return false;
      if (Airport != other.Airport) return false;
      if (NoPlaces != other.NoPlaces) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FlightID != 0) hash ^= FlightID.GetHashCode();
      if (Destination.Length != 0) hash ^= Destination.GetHashCode();
      if (Datetime.Length != 0) hash ^= Datetime.GetHashCode();
      if (Airport.Length != 0) hash ^= Airport.GetHashCode();
      if (NoPlaces != 0) hash ^= NoPlaces.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FlightID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(FlightID);
      }
      if (Destination.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Destination);
      }
      if (Datetime.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Datetime);
      }
      if (Airport.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Airport);
      }
      if (NoPlaces != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NoPlaces);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FlightID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(FlightID);
      }
      if (Destination.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Destination);
      }
      if (Datetime.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Datetime);
      }
      if (Airport.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Airport);
      }
      if (NoPlaces != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NoPlaces);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FlightID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FlightID);
      }
      if (Destination.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Destination);
      }
      if (Datetime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Datetime);
      }
      if (Airport.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Airport);
      }
      if (NoPlaces != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NoPlaces);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Flight other) {
      if (other == null) {
        return;
      }
      if (other.FlightID != 0) {
        FlightID = other.FlightID;
      }
      if (other.Destination.Length != 0) {
        Destination = other.Destination;
      }
      if (other.Datetime.Length != 0) {
        Datetime = other.Datetime;
      }
      if (other.Airport.Length != 0) {
        Airport = other.Airport;
      }
      if (other.NoPlaces != 0) {
        NoPlaces = other.NoPlaces;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FlightID = input.ReadInt32();
            break;
          }
          case 18: {
            Destination = input.ReadString();
            break;
          }
          case 26: {
            Datetime = input.ReadString();
            break;
          }
          case 34: {
            Airport = input.ReadString();
            break;
          }
          case 40: {
            NoPlaces = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FlightID = input.ReadInt32();
            break;
          }
          case 18: {
            Destination = input.ReadString();
            break;
          }
          case 26: {
            Datetime = input.ReadString();
            break;
          }
          case 34: {
            Airport = input.ReadString();
            break;
          }
          case 40: {
            NoPlaces = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Ticket : pb::IMessage<Ticket>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Ticket> _parser = new pb::MessageParser<Ticket>(() => new Ticket());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Ticket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Agency.Network.Protobuffprotocol.AgencyProtocolReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ticket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ticket(Ticket other) : this() {
      clientName_ = other.clientName_;
      touristNames_ = other.touristNames_;
      clientAddress_ = other.clientAddress_;
      noPlaces_ = other.noPlaces_;
      flight_ = other.flight_ != null ? other.flight_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ticket Clone() {
      return new Ticket(this);
    }

    /// <summary>Field number for the "clientName" field.</summary>
    public const int ClientNameFieldNumber = 1;
    private string clientName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientName {
      get { return clientName_; }
      set {
        clientName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "touristNames" field.</summary>
    public const int TouristNamesFieldNumber = 2;
    private string touristNames_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TouristNames {
      get { return touristNames_; }
      set {
        touristNames_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "clientAddress" field.</summary>
    public const int ClientAddressFieldNumber = 3;
    private string clientAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientAddress {
      get { return clientAddress_; }
      set {
        clientAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "noPlaces" field.</summary>
    public const int NoPlacesFieldNumber = 4;
    private int noPlaces_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NoPlaces {
      get { return noPlaces_; }
      set {
        noPlaces_ = value;
      }
    }

    /// <summary>Field number for the "flight" field.</summary>
    public const int FlightFieldNumber = 5;
    private global::Agency.Network.Protobuffprotocol.Flight flight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Agency.Network.Protobuffprotocol.Flight Flight {
      get { return flight_; }
      set {
        flight_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Ticket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Ticket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientName != other.ClientName) return false;
      if (TouristNames != other.TouristNames) return false;
      if (ClientAddress != other.ClientAddress) return false;
      if (NoPlaces != other.NoPlaces) return false;
      if (!object.Equals(Flight, other.Flight)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientName.Length != 0) hash ^= ClientName.GetHashCode();
      if (TouristNames.Length != 0) hash ^= TouristNames.GetHashCode();
      if (ClientAddress.Length != 0) hash ^= ClientAddress.GetHashCode();
      if (NoPlaces != 0) hash ^= NoPlaces.GetHashCode();
      if (flight_ != null) hash ^= Flight.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientName);
      }
      if (TouristNames.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TouristNames);
      }
      if (ClientAddress.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ClientAddress);
      }
      if (NoPlaces != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NoPlaces);
      }
      if (flight_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Flight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientName);
      }
      if (TouristNames.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TouristNames);
      }
      if (ClientAddress.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ClientAddress);
      }
      if (NoPlaces != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NoPlaces);
      }
      if (flight_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Flight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ClientName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientName);
      }
      if (TouristNames.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TouristNames);
      }
      if (ClientAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientAddress);
      }
      if (NoPlaces != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NoPlaces);
      }
      if (flight_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Flight);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Ticket other) {
      if (other == null) {
        return;
      }
      if (other.ClientName.Length != 0) {
        ClientName = other.ClientName;
      }
      if (other.TouristNames.Length != 0) {
        TouristNames = other.TouristNames;
      }
      if (other.ClientAddress.Length != 0) {
        ClientAddress = other.ClientAddress;
      }
      if (other.NoPlaces != 0) {
        NoPlaces = other.NoPlaces;
      }
      if (other.flight_ != null) {
        if (flight_ == null) {
          Flight = new global::Agency.Network.Protobuffprotocol.Flight();
        }
        Flight.MergeFrom(other.Flight);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ClientName = input.ReadString();
            break;
          }
          case 18: {
            TouristNames = input.ReadString();
            break;
          }
          case 26: {
            ClientAddress = input.ReadString();
            break;
          }
          case 32: {
            NoPlaces = input.ReadInt32();
            break;
          }
          case 42: {
            if (flight_ == null) {
              Flight = new global::Agency.Network.Protobuffprotocol.Flight();
            }
            input.ReadMessage(Flight);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ClientName = input.ReadString();
            break;
          }
          case 18: {
            TouristNames = input.ReadString();
            break;
          }
          case 26: {
            ClientAddress = input.ReadString();
            break;
          }
          case 32: {
            NoPlaces = input.ReadInt32();
            break;
          }
          case 42: {
            if (flight_ == null) {
              Flight = new global::Agency.Network.Protobuffprotocol.Flight();
            }
            input.ReadMessage(Flight);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class AgencyRequest : pb::IMessage<AgencyRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AgencyRequest> _parser = new pb::MessageParser<AgencyRequest>(() => new AgencyRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AgencyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Agency.Network.Protobuffprotocol.AgencyProtocolReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgencyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgencyRequest(AgencyRequest other) : this() {
      type_ = other.type_;
      employee_ = other.employee_ != null ? other.employee_.Clone() : null;
      filterDataArray_ = other.filterDataArray_ != null ? other.filterDataArray_.Clone() : null;
      ticket_ = other.ticket_ != null ? other.ticket_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgencyRequest Clone() {
      return new AgencyRequest(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Agency.Network.Protobuffprotocol.AgencyRequest.Types.Type type_ = global::Agency.Network.Protobuffprotocol.AgencyRequest.Types.Type.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Agency.Network.Protobuffprotocol.AgencyRequest.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "employee" field.</summary>
    public const int EmployeeFieldNumber = 2;
    private global::Agency.Network.Protobuffprotocol.Employee employee_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Agency.Network.Protobuffprotocol.Employee Employee {
      get { return employee_; }
      set {
        employee_ = value;
      }
    }

    /// <summary>Field number for the "filter_data_array" field.</summary>
    public const int FilterDataArrayFieldNumber = 3;
    private global::Agency.Network.Protobuffprotocol.FilterData filterDataArray_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Agency.Network.Protobuffprotocol.FilterData FilterDataArray {
      get { return filterDataArray_; }
      set {
        filterDataArray_ = value;
      }
    }

    /// <summary>Field number for the "ticket" field.</summary>
    public const int TicketFieldNumber = 4;
    private global::Agency.Network.Protobuffprotocol.Ticket ticket_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Agency.Network.Protobuffprotocol.Ticket Ticket {
      get { return ticket_; }
      set {
        ticket_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AgencyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AgencyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Employee, other.Employee)) return false;
      if (!object.Equals(FilterDataArray, other.FilterDataArray)) return false;
      if (!object.Equals(Ticket, other.Ticket)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Agency.Network.Protobuffprotocol.AgencyRequest.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (employee_ != null) hash ^= Employee.GetHashCode();
      if (filterDataArray_ != null) hash ^= FilterDataArray.GetHashCode();
      if (ticket_ != null) hash ^= Ticket.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Agency.Network.Protobuffprotocol.AgencyRequest.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (employee_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Employee);
      }
      if (filterDataArray_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FilterDataArray);
      }
      if (ticket_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Ticket);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Agency.Network.Protobuffprotocol.AgencyRequest.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (employee_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Employee);
      }
      if (filterDataArray_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FilterDataArray);
      }
      if (ticket_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Ticket);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Agency.Network.Protobuffprotocol.AgencyRequest.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (employee_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Employee);
      }
      if (filterDataArray_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FilterDataArray);
      }
      if (ticket_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ticket);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AgencyRequest other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Agency.Network.Protobuffprotocol.AgencyRequest.Types.Type.Unknown) {
        Type = other.Type;
      }
      if (other.employee_ != null) {
        if (employee_ == null) {
          Employee = new global::Agency.Network.Protobuffprotocol.Employee();
        }
        Employee.MergeFrom(other.Employee);
      }
      if (other.filterDataArray_ != null) {
        if (filterDataArray_ == null) {
          FilterDataArray = new global::Agency.Network.Protobuffprotocol.FilterData();
        }
        FilterDataArray.MergeFrom(other.FilterDataArray);
      }
      if (other.ticket_ != null) {
        if (ticket_ == null) {
          Ticket = new global::Agency.Network.Protobuffprotocol.Ticket();
        }
        Ticket.MergeFrom(other.Ticket);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Agency.Network.Protobuffprotocol.AgencyRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (employee_ == null) {
              Employee = new global::Agency.Network.Protobuffprotocol.Employee();
            }
            input.ReadMessage(Employee);
            break;
          }
          case 26: {
            if (filterDataArray_ == null) {
              FilterDataArray = new global::Agency.Network.Protobuffprotocol.FilterData();
            }
            input.ReadMessage(FilterDataArray);
            break;
          }
          case 34: {
            if (ticket_ == null) {
              Ticket = new global::Agency.Network.Protobuffprotocol.Ticket();
            }
            input.ReadMessage(Ticket);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Agency.Network.Protobuffprotocol.AgencyRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (employee_ == null) {
              Employee = new global::Agency.Network.Protobuffprotocol.Employee();
            }
            input.ReadMessage(Employee);
            break;
          }
          case 26: {
            if (filterDataArray_ == null) {
              FilterDataArray = new global::Agency.Network.Protobuffprotocol.FilterData();
            }
            input.ReadMessage(FilterDataArray);
            break;
          }
          case 34: {
            if (ticket_ == null) {
              Ticket = new global::Agency.Network.Protobuffprotocol.Ticket();
            }
            input.ReadMessage(Ticket);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AgencyRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Login")] Login = 1,
        [pbr::OriginalName("Logout")] Logout = 2,
        [pbr::OriginalName("Get_flights")] GetFlights = 3,
        [pbr::OriginalName("Buy_ticket")] BuyTicket = 4,
        [pbr::OriginalName("Filter_flights")] FilterFlights = 5,
      }

    }
    #endregion

  }

  public sealed partial class AgencyResponse : pb::IMessage<AgencyResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AgencyResponse> _parser = new pb::MessageParser<AgencyResponse>(() => new AgencyResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AgencyResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Agency.Network.Protobuffprotocol.AgencyProtocolReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgencyResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgencyResponse(AgencyResponse other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      flights_ = other.flights_.Clone();
      employee_ = other.employee_ != null ? other.employee_.Clone() : null;
      ticket_ = other.ticket_ != null ? other.ticket_.Clone() : null;
      flight_ = other.flight_ != null ? other.flight_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgencyResponse Clone() {
      return new AgencyResponse(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Agency.Network.Protobuffprotocol.AgencyResponse.Types.Type type_ = global::Agency.Network.Protobuffprotocol.AgencyResponse.Types.Type.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Agency.Network.Protobuffprotocol.AgencyResponse.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "flights" field.</summary>
    public const int FlightsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Agency.Network.Protobuffprotocol.Flight> _repeated_flights_codec
        = pb::FieldCodec.ForMessage(26, global::Agency.Network.Protobuffprotocol.Flight.Parser);
    private readonly pbc::RepeatedField<global::Agency.Network.Protobuffprotocol.Flight> flights_ = new pbc::RepeatedField<global::Agency.Network.Protobuffprotocol.Flight>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Agency.Network.Protobuffprotocol.Flight> Flights {
      get { return flights_; }
    }

    /// <summary>Field number for the "employee" field.</summary>
    public const int EmployeeFieldNumber = 4;
    private global::Agency.Network.Protobuffprotocol.Employee employee_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Agency.Network.Protobuffprotocol.Employee Employee {
      get { return employee_; }
      set {
        employee_ = value;
      }
    }

    /// <summary>Field number for the "ticket" field.</summary>
    public const int TicketFieldNumber = 5;
    private global::Agency.Network.Protobuffprotocol.Ticket ticket_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Agency.Network.Protobuffprotocol.Ticket Ticket {
      get { return ticket_; }
      set {
        ticket_ = value;
      }
    }

    /// <summary>Field number for the "flight" field.</summary>
    public const int FlightFieldNumber = 6;
    private global::Agency.Network.Protobuffprotocol.Flight flight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Agency.Network.Protobuffprotocol.Flight Flight {
      get { return flight_; }
      set {
        flight_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AgencyResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AgencyResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if(!flights_.Equals(other.flights_)) return false;
      if (!object.Equals(Employee, other.Employee)) return false;
      if (!object.Equals(Ticket, other.Ticket)) return false;
      if (!object.Equals(Flight, other.Flight)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Agency.Network.Protobuffprotocol.AgencyResponse.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      hash ^= flights_.GetHashCode();
      if (employee_ != null) hash ^= Employee.GetHashCode();
      if (ticket_ != null) hash ^= Ticket.GetHashCode();
      if (flight_ != null) hash ^= Flight.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Agency.Network.Protobuffprotocol.AgencyResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      flights_.WriteTo(output, _repeated_flights_codec);
      if (employee_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Employee);
      }
      if (ticket_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Ticket);
      }
      if (flight_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Flight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Agency.Network.Protobuffprotocol.AgencyResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      flights_.WriteTo(ref output, _repeated_flights_codec);
      if (employee_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Employee);
      }
      if (ticket_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Ticket);
      }
      if (flight_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Flight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Agency.Network.Protobuffprotocol.AgencyResponse.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      size += flights_.CalculateSize(_repeated_flights_codec);
      if (employee_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Employee);
      }
      if (ticket_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ticket);
      }
      if (flight_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Flight);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AgencyResponse other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Agency.Network.Protobuffprotocol.AgencyResponse.Types.Type.Unknown) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      flights_.Add(other.flights_);
      if (other.employee_ != null) {
        if (employee_ == null) {
          Employee = new global::Agency.Network.Protobuffprotocol.Employee();
        }
        Employee.MergeFrom(other.Employee);
      }
      if (other.ticket_ != null) {
        if (ticket_ == null) {
          Ticket = new global::Agency.Network.Protobuffprotocol.Ticket();
        }
        Ticket.MergeFrom(other.Ticket);
      }
      if (other.flight_ != null) {
        if (flight_ == null) {
          Flight = new global::Agency.Network.Protobuffprotocol.Flight();
        }
        Flight.MergeFrom(other.Flight);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Agency.Network.Protobuffprotocol.AgencyResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            flights_.AddEntriesFrom(input, _repeated_flights_codec);
            break;
          }
          case 34: {
            if (employee_ == null) {
              Employee = new global::Agency.Network.Protobuffprotocol.Employee();
            }
            input.ReadMessage(Employee);
            break;
          }
          case 42: {
            if (ticket_ == null) {
              Ticket = new global::Agency.Network.Protobuffprotocol.Ticket();
            }
            input.ReadMessage(Ticket);
            break;
          }
          case 50: {
            if (flight_ == null) {
              Flight = new global::Agency.Network.Protobuffprotocol.Flight();
            }
            input.ReadMessage(Flight);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Agency.Network.Protobuffprotocol.AgencyResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            flights_.AddEntriesFrom(ref input, _repeated_flights_codec);
            break;
          }
          case 34: {
            if (employee_ == null) {
              Employee = new global::Agency.Network.Protobuffprotocol.Employee();
            }
            input.ReadMessage(Employee);
            break;
          }
          case 42: {
            if (ticket_ == null) {
              Ticket = new global::Agency.Network.Protobuffprotocol.Ticket();
            }
            input.ReadMessage(Ticket);
            break;
          }
          case 50: {
            if (flight_ == null) {
              Flight = new global::Agency.Network.Protobuffprotocol.Flight();
            }
            input.ReadMessage(Flight);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AgencyResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Ok")] Ok = 1,
        [pbr::OriginalName("Error")] Error = 2,
        [pbr::OriginalName("Get_flights")] GetFlights = 3,
        [pbr::OriginalName("Update_flights")] UpdateFlights = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
